---
- name: Deploy Node.js App using Docker
  hosts: web
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Login to DockerHub (optional, only if using private repo)
      docker_login:
        username: "{{ docker_username | default(omit) }}"
        password: "{{ docker_password | default(omit) }}"
      when: docker_username is defined and docker_password is defined

    - name: Pull app image from DockerHub
      docker_image:
        name: sahilc08/myapp
        tag: latest
        source: pull

    - name: Remove existing container if exists
      docker_container:
        name: myapp
        state: absent
        force_kill: true

    - name: Run Docker container
      docker_container:
        name: myapp
        image: sahilc08/myapp:latest
        state: started
        restart_policy: always
        ports:
          - "80:3000"

